# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_facebook_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='external_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='external_link_text',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
